name: eslint checks

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: npx eslint ./src
